### PR TITLE
ELK-BLEDOM Spotify Song update

### PR DESCRIPTION
**Pull request by Shadeys**

### CODE REVIEW

**Review by Shadeys — COMMENTED** [review]
Great

**Review by Shadeys — COMMENTED** [review]
Add "this." to spotify.js

**Comment by Amenofisch** [comment]
If you're already changing code, then you should be adjusting the tests too, as long as they fail I won't be able to merge this. Also I'm not sure what you meant by "add this. to spotify.js". I'd really appreciate if you'd take the time to look over your code yourself and atleast try to run it using nodejs, if that fails then don't even bother to ask me that i should test it. I'm not here to fix the code that you've produced and it's not working.

**Comment by Amenofisch** [comment]
Also please properly name your commits from now.

**Comment by Shadeys** [comment]
It's my mistake, i forgot to paste the code from Repl.it

**Comment by Shadeys** [comment]
I don't know why it's checking again, i just uploaded a favicon.ico.

**Comment by Amenofisch** [comment]
I was the one who executed the workflow. Is it ready to take a look at or do you need more time?

**Comment by Shadeys** [comment]
it's ready

**Comment by Shadeys** [comment]
btw add me on discord DShadeyy#8180

**Comment by Shadeys** [comment]
What are the conflicting files? There are no errors!!

**Comment by Shadeys** [comment]
i will close the pull request, unless the status is reported.

**Comment by Shadeys** [comment]
Can you review the pull request? And of course for the 100x time add me on discord DShadeyy#8180

**Review by Shadeys — COMMENTED** [review]
Checked for error's my self and there are currently none being presented to me.

**Comment by Amenofisch** [comment]
Hey, could you fix the conflicts? Oh and sorry for not saying anything about discord, i forgot my password and was lazy to reset it.

**Pull request closed without merging**
